sudo: required

services:
  - docker

before_install:
  - docker build -t lucypowalowska/frontend -f ./other-labs/frontend/Dockerfile.dev ./other-labs/frontend

script:
  - docker run -e CI=true lucypowalowska/frontend yarn test
